import { SiteLayout } from "@/components/SiteLayout";
import { Helmet } from "react-helmet-async";

export default function TermsPage() {
  return (
    <SiteLayout>
      <Helmet>
        <title>Terms of Service - Restnvest</title>
        <meta name="description" content="Restnvest Terms of Service — the rules and guidelines governing your use of our AI-powered stock research platform." />
        <meta property="og:title" content="Terms of Service - Restnvest" />
        <meta property="og:description" content="Terms of Service governing the use of Restnvest's AI-powered stock research platform." />
        <meta property="og:type" content="website" />
        <link rel="canonical" href="https://restnvest.com/terms" />
      </Helmet>

      <section className="py-16 sm:py-20 lg:py-24 px-4 sm:px-6 lg:px-8" data-testid="section-terms">
        <div className="mx-auto max-w-3xl">
          <h1 className="text-3xl sm:text-4xl font-bold tracking-tight mb-2" data-testid="text-terms-headline">
            Terms of Service
          </h1>
          <p className="text-sm text-muted-foreground mb-10" data-testid="text-terms-date">
            Last updated: February 2026
          </p>

          <div className="prose prose-sm dark:prose-invert max-w-none space-y-8 text-muted-foreground leading-relaxed">
            <div className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">1. Acceptance of Terms</h2>
              <p>
                By accessing or using Restnvest ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service. We reserve the right to update these terms at any time, and your continued use of the Service constitutes acceptance of any changes.
              </p>
            </div>

            <div className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">2. Description of Service</h2>
              <p>
                Restnvest provides AI-powered analysis of publicly available SEC 10-K filings to help users understand public companies. The Service transforms complex financial documents into structured, readable summaries and analysis.
              </p>
            </div>

            <div className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">3. Not Investment Advice</h2>
              <p>
                The information provided by Restnvest is for informational and educational purposes only. It does not constitute investment advice, financial advice, trading advice, or any other sort of advice. You should not treat any of the content on Restnvest as such. Restnvest does not recommend that any security, portfolio of securities, transaction, or investment strategy is suitable for any specific person.
              </p>
              <p>
                Any investment decisions you make are solely your responsibility. You should consult with a qualified financial advisor before making any investment decisions. Past performance of any security is not indicative of future results.
              </p>
            </div>

            <div className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">4. Accuracy of Information</h2>
              <p>
                While we strive to provide accurate analysis, Restnvest relies on AI-generated summaries of SEC filings. These summaries may contain errors, omissions, or misinterpretations. The Service is provided "as is" and we make no warranties regarding the accuracy, completeness, or reliability of any content.
              </p>
              <p>
                Source data comes from the SEC's EDGAR database. While EDGAR is an authoritative source, Restnvest is not affiliated with or endorsed by the U.S. Securities and Exchange Commission.
              </p>
            </div>

            <div className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">5. User Conduct</h2>
              <p>You agree not to:</p>
              <ul className="list-disc pl-5 space-y-1">
                <li>Use the Service for any unlawful purpose</li>
                <li>Attempt to interfere with or disrupt the Service</li>
                <li>Scrape, crawl, or use automated means to access the Service beyond normal use</li>
                <li>Redistribute or resell the content generated by the Service without permission</li>
                <li>Misrepresent AI-generated analysis as professional financial advice</li>
              </ul>
            </div>

            <div className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">6. Intellectual Property</h2>
              <p>
                The Service, including its design, code, and AI analysis methodology, is the property of Restnvest. The underlying SEC filing data is public information. You may use the analysis generated by the Service for personal, non-commercial purposes.
              </p>
            </div>

            <div className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">7. Limitation of Liability</h2>
              <p>
                To the maximum extent permitted by law, Restnvest and its team shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from your use of the Service.
              </p>
            </div>

            <div className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">8. Service Availability</h2>
              <p>
                We do not guarantee that the Service will be available at all times. We may suspend or discontinue the Service at any time without notice. We are not liable for any modification, suspension, or discontinuation of the Service.
              </p>
            </div>

            <div className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">9. Contact</h2>
              <p>
                If you have questions about these Terms, please contact us at{" "}
                <a href="mailto:hello@restnvest.com" className="text-primary hover:underline">
                  hello@restnvest.com
                </a>.
              </p>
            </div>
          </div>
        </div>
      </section>
    </SiteLayout>
  );
}
